package sky.starry.community.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Update;
import sky.starry.community.model.Comment;
import sky.starry.community.model.Question;


public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Fri Jul 24 23:36:47 CST 2020
     */
    Comment selectByPrimaryKey(Long id);

    void insertComment(Comment comment);

    @Update("update comment set comment_count=comment_count+#{commentCount} where id = #{id};")
    void incCommentCount(Comment comment);
}