package sky.starry.community.mapper;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import sky.starry.community.model.Question;

import java.util.List;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jul 25 16:54:27 CST 2020
     */
    Question selectByPrimaryKey(Long id);

    @Insert("insert into question(title,description,gmt_create,gmt_modified,creator,tag) values (#{title},#{description},#{gmtCreate},#{gmtModified},#{creator},#{tag})")
    void create(Question question);

    @Select("select * from question order by gmt_create desc limit #{offset},#{size};")
    List<Question> list(@Param("offset") Integer offset, @Param("size") Integer size);

    @Select("select count(1) from question;")
    Integer count();

    @Select("select count(1) from question where creator = #{userId};")
    Integer countByUserId(@Param("userId") Long userId);

    @Select("select * from question where creator = #{userId} limit #{offset},#{size};")
    List<Question> listByUserId(@Param("userId") Long userId,@Param("offset") Integer offset,@Param("size") Integer size);

    @Select("select * from question where id = #{id};")
    Question getById(@Param("id") Long id);

    @Update("update question set title = #{title},description = #{description},gmt_modified = #{gmtModified},tag = #{tag} where id = #{id}")
    int update(Question question);

    @Update("update question set view_count=view_count+#{viewCount} where id = #{id};")
    void incView(Question question);

    @Update("update question set comment_count=comment_count+#{commentCount} where id = #{id};")
    void incCommentCount(Question question);

    List<Question> selectRelated(Question question);
}
